# Create a GitHub action to email a report from a file at 6 a.m. daily.
name: Email report

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Email report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Daily report
          body: Daily report attached.
          to: ${{ secrets.EMAIL_TO }}
          attachments: path/to/report.txt
```

## 7. Create a GitHub action to deploy an app
Create a GitHub action to deploy an app to a server when changes are pushed to the `main` branch.

```yaml
# Path: deploy-app.yml
# Create a GitHub action to deploy an app to a server when changes are pushed to the main branch.
name: Deploy app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy app
        run: |
          # Add commands to deploy the app here.
```

## 8. Create a GitHub action to build and test a Python app
Create a GitHub action to build and test a Python app when changes are pushed to the `main` branch.

```yaml
# Path: build-and-test.yml
# Create a GitHub action to build and test a Python app when changes are pushed to the main branch.
name: Build and test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
```

## 9. Create a GitHub action to build and test a Node.js app
Create a GitHub action to build and test a Node.js app when changes are pushed to the `main` branch.

```yaml
# Path: build-and-test.yml
#